<?php

/**
 * ACF - custom block card links to pages
 *
 * @package    	Casino_Toolbox
 * @link        //
 * Author:      Andrei Dragomir
 * License URI: http://www.gnu.org/licenses/gpl-2.0.txt
 */

if( function_exists('acf_register_block_type') ):

	acf_register_block_type(array(
		'name' => 'blockcardlinks',
		'title' => 'Block - Card Links',
		'description' => 'Card Links',
		'category' => 'casino-toolbox',
		'keywords' => array(
			0 => 'card',
			1 => 'links',
			2 => 'pages'
		),
		'post_types' => array(
		),
		'mode' => 'edit',
		'align' => 'wide',
		'render_template' => CC_DIR . 'inc/ACF/acf-templates/acf-template-card-links.php',
		'render_callback' => '',
		'enqueue_assets' => '',
		'icon' => '<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="dollar-sign" class="svg-inline--fa fa-dollar-sign fa-w-9" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 288 512"><path fill="currentColor" d="M209.2 233.4l-108-31.6C88.7 198.2 80 186.5 80 173.5c0-16.3 13.2-29.5 29.5-29.5h66.3c12.2 0 24.2 3.7 34.2 10.5 6.1 4.1 14.3 3.1 19.5-2l34.8-34c7.1-6.9 6.1-18.4-1.8-24.5C238 74.8 207.4 64.1 176 64V16c0-8.8-7.2-16-16-16h-32c-8.8 0-16 7.2-16 16v48h-2.5C45.8 64-5.4 118.7.5 183.6c4.2 46.1 39.4 83.6 83.8 96.6l102.5 30c12.5 3.7 21.2 15.3 21.2 28.3 0 16.3-13.2 29.5-29.5 29.5h-66.3C100 368 88 364.3 78 357.5c-6.1-4.1-14.3-3.1-19.5 2l-34.8 34c-7.1 6.9-6.1 18.4 1.8 24.5 24.5 19.2 55.1 29.9 86.5 30v48c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16v-48.2c46.6-.9 90.3-28.6 105.7-72.7 21.5-61.6-14.6-124.8-72.5-141.7z"></path></svg>',
		'supports' => array(
			'align' => false,
			'mode' => true,
			'multiple' => true,
		),
	));

	acf_add_local_field_group(array(
		'key' => 'group_63c65bfa63d1b',
    'title' => 'Block - Card Links',
		'fields' => array(
      array(
        'key' => 'field_63c66184d8d73',
        'label' => 'Blue Card',
        'name' => 'blue_card',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'acfe_seamless_style' => 0,
        'acfe_group_modal' => 0,
        'sub_fields' => array(
          array(
            'key' => 'field_63c661edd8d75',
            'label' => 'Page 1',
            'name' => 'page_1',
            'type' => 'post_object',
            'instructions' => 'Alege pagina catre care vrei sa trimiti utilizatorul.',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'page',
            ),
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'object',
            'save_custom' => 0,
            'save_post_status' => 'publish',
            'acfe_bidirectional' => array(
              'acfe_bidirectional_enabled' => '0',
            ),
            'ui' => 1,
            'save_post_type' => '',
          ),
          array(
            'key' => 'field_63c66214d8d76',
            'label' => 'Card Image 1',
            'name' => 'card_image_1',
            'type' => 'image',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'uploader' => '',
            'acfe_thumbnail' => 0,
            'return_format' => 'array',
            'preview_size' => 'medium',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'library' => 'all',
          ),
          array(
            'key' => 'field_63c6623ad8d77',
            'label' => 'Card Title 1',
            'name' => 'card_title_1',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_63c66243d8d78',
            'label' => 'Card Text 1',
            'name' => 'card_text_1',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 1,
          ),
          array(
            'key' => 'field_63c6624ed8d79',
            'label' => 'Card Button Text 1',
            'name' => 'card_button_text_1',
            'type' => 'text',
            'instructions' => 'Scrie ce text vrei sa apara pe buton.',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
        ),
        'acfe_group_modal_close' => 0,
        'acfe_group_modal_button' => '',
        'acfe_group_modal_size' => 'large',
      ),
      array(
        'key' => 'field_63c661d5d8d74',
        'label' => 'Green Card',
        'name' => 'green_card',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'acfe_seamless_style' => 0,
        'acfe_group_modal' => 0,
        'sub_fields' => array(
          array(
            'key' => 'field_63c66289d8d7a',
            'label' => 'Page 2',
            'name' => 'page_2',
            'type' => 'post_object',
            'instructions' => 'Alege pagina catre care vrei sa trimiti utilizatorul.',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'post_type' => '',
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'object',
            'save_custom' => 0,
            'save_post_status' => 'publish',
            'acfe_bidirectional' => array(
              'acfe_bidirectional_enabled' => '0',
            ),
            'ui' => 1,
            'save_post_type' => '',
          ),
          array(
            'key' => 'field_63c662ded8d7b',
            'label' => 'Card Image 2',
            'name' => 'card_image_2',
            'type' => 'image',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'uploader' => '',
            'acfe_thumbnail' => 0,
            'return_format' => 'array',
            'preview_size' => 'medium',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'library' => 'all',
          ),
          array(
            'key' => 'field_63c662fdd8d7c',
            'label' => 'Card Title 2',
            'name' => 'card_title_2',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_63c6632ad8d7d',
            'label' => 'Card Text 2',
            'name' => 'card_text_2',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 1,
          ),
          array(
            'key' => 'field_63c66339d8d7f',
            'label' => 'Card Button Text 2',
            'name' => 'card_button_text_2',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
        ),
        'acfe_group_modal_close' => 0,
        'acfe_group_modal_button' => '',
        'acfe_group_modal_size' => 'large',
      ),
    ),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/blockcardlinks',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_permissions' => '',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
	));

endif;